### PR TITLE
Move of obsolete classes 

### PR DESCRIPTION
**Pull request by rubsy92**
Moving the obsolete classes to a seperate project. Note that there are build errors in the legacy project since the namespaces don't match anymore.

### CODE REVIEW

**Comment by epsi1on** [comment]
Does the project build successfully? Seems checks are failed...

**Comment by rubsy92** [comment]
The obsolete project contains a hard copy of all obsolete classes so they can be copied back if needed. Therefore it doesn´t build (since the namespaces aren´t changed). I can change the namespaces if you want?

**Comment by epsi1on** [comment]
Hi,
Yes better to change namespace and let project be built successfully.
Thanks

**Comment by rubsy92** [comment]
Hi @epsi1on 

It should build now, can you check please?

**Comment by epsi1on** [comment]
seems you did commented out many codes. I'll handle this issue, OK?

**Comment by rubsy92** [comment]
Sure, since you'll know better what's oboslete and whats not.

**Comment by epsi1on** [comment]
#89

**Pull request closed without merging**
