### PR TITLE
BriefFiniteElementNet.Controls: use OxyPlot instead of DynamicDataDisplay

### PR DESCRIPTION
**Pull request by wo80**
This PR also removes `BriefFiniteElementNet.DebuggerVisualizers-VS2019.csproj` and uses the `BriefFiniteElementNet.DebuggerVisualizers.csproj` project file instead.

@epsi1on I guess no one of us can check, if the older debugger visualizer project files still work. Should they be removed with this PR?

### CODE REVIEW

**Comment by wo80** [comment]
Additionally, I was wondering if the automatic copying of the files in the PostBuildEvent should be removed?

**Comment by epsi1on** [comment]
I'm OK with OxyPlot,

> Additionally, I was wondering if the automatic copying of the files in the PostBuildEvent of `BriefFiniteElementNet.DebuggerVisualizers` should be removed?

That is for automatic installation of debugger visualizers after each build. I think it should not be removed. Just need to disable build of visualizers project when solution is build, if a user want to build and install visualizer, then he should build the visualizer project separately

**Comment by wo80** [comment]
What about deleting the old debugger visualizer project files?

Feel free to merge, if you think we're done here.

**Comment by epsi1on** [comment]
That would be good, once we are removing compatibility with older VisualStudio versions, we should make ready the nuget package.

**Comment by wo80** [comment]
This should be ready to merge.

**Pull request merged**
