### PR TITLE
Update 23.06.2020

### PR DESCRIPTION
**Pull request by thaletob**

### CODE REVIEW

**Comment by thaletob** [comment]
While testing I recognized an error in Q4MembraneHelper -> GetAMatrix -> detJ is throwing an error because of an empty matrix J. I'm trying to fix it tomorrow.

**Comment by thaletob** [comment]
Your DKQElementHelper did not draw any errors while testing, so it should be okay! :)

**Comment by epsi1on** [comment]
I'll check your code ASAP

**Comment by thaletob** [comment]
The Error was actually caused by missing brackets in the allocation of Matrix J in my Q4MembraneHelper-class.

**Comment by thaletob** [comment]
Only one Error during the solving-process left. I have not implemented `QuadBasicDrillingDof` yet.

**Comment by epsi1on** [comment]
Actually the DKQ or Q4 do not carry torsional force (drilling dof), so an approx value is set for that on stiffness matrix.

**Comment by thaletob** [comment]
So you think this class is neccessary?

**Comment by epsi1on** [comment]
Yes, otherwise you’ll get Not Positive Definite exception

**Comment by thaletob** [comment]
Okay that is exactly what I've got in my last error. Thanks for the hint!

**Comment by thaletob** [comment]
I actually added the class which is nearly the same as `TriangleBasicDrillingDofHelper.cs`. But still getting the error you described.

**Comment by epsi1on** [comment]
OK, I'll check

**Pull request merged**
