### PR TITLE
Fix bug issue #76 according to epsi1on + Validation triangular shell

### PR DESCRIPTION
**Pull request by rubsy92**
Validation case flat plate, STRI3 Abaqus

### CODE REVIEW

**Comment by epsi1on** [comment]
Thanks, this is very nice.
Can you please replace xlsx excel file with a plain text csv file?

**Comment by rubsy92** [comment]
Changed

**Review by epsi1on — APPROVED** [review]

**Comment by epsi1on** [comment]
Validations update + minor update

**Comment by epsi1on** [comment]
Hi, I did resolve some conflicts. but now gives error

``` Data\FlatShell - triangle\FlatPlate\Validator.cs(1,29): error CS0234: The type or namespace name 'DebuggerVisualizers' does not exist in the namespace 'BriefFiniteElementNet' (are you missing an assembly reference?) [C:\projects\brieffiniteelement-net\BriefFiniteElementNet.Validation\BriefFiniteElementNet.Validation.csproj] ```

Can you please have a look? Changes are applied in your fork of BFE

Thanks

**Comment by rubsy92** [comment]
I removed the DebuggerVisualizers (only used to view the sample, so it's not really needed for a validation standpoint)

**Review by epsi1on — APPROVED** [review]

**Pull request merged**
