### PR TITLE
Update 22.06.20

### PR DESCRIPTION
**Pull request by thaletob**
Added the missing Matrix calculations with respect to xi and eta.
What is meant by the function GetBMaxOrder ? I don't understand what it is...

### CODE REVIEW

**Comment by epsi1on** [comment]
GetBMaxOrder() is used inside integration for determining sampling point

**Comment by thaletob** [comment]
Yes, but the structure of the contained vector is not clear to me... does it contain the max. degree of each row of B? Or how does it work?

**Comment by epsi1on** [comment]
it is int[] array, usually, three members. first is max degree of `Xi`, second and third is for other isoparametric dimensions. for 1D elements, only first member have value, for 2D, first two elements and for 3D, all elements.

**Comment by thaletob** [comment]
Thank you, this helped a lot.

**Comment by thaletob** [comment]
I think I only need to complete the QuadrilaturalElement.cs class now before the Elementtype is ready for testing. Am I right?

**Comment by thaletob** [comment]
I am asking because it is actually pretty hard to keep an overview over all classes and functions and how they hang together when you have not written the whole code on your own. I am trying to get this Element-Type working properly within the following days.
Kind regards.

**Comment by epsi1on** [comment]
> I am asking because it is actually pretty hard to keep an overview over all classes and functions and how they hang together when you have not written the whole code on your own. I am trying to get this Element-Type working properly within the following days.
> Kind regards.
There are two approaches for testing, one is unit testing and other one is integrated testing. 

- Unit Test is test for each single part (single method like IElementHelper.GetBMatrix()) and compare result with a reference (like another implementation or another software)
- Integrated test is to test the whole code, in our example a full model with external loads and finally compare nodal displacements with reference application

There is only one thing and that is `NotImplementException`s and we can see if it throws any in action! :)

example of integrated test is in here for triangle element:

 BriefFiniteElement.Net/BriefFiniteElementNet.Validation/TriangleElementTester.cs 
 
It compares result of nodal displacement with opensees. i think you better create a class with name `QuadrilaturalElementTester.cs` which is a copy of this file.

**Comment by epsi1on** [comment]
> 
> 
> I am asking because it is actually pretty hard to keep an overview over all classes and functions and how they hang together when you have not written the whole code on your own. I am trying to get this Element-Type working properly within the following days.
> Kind regards.

Actually my target was to decouple implementation of different elements, so there is a main element which is a state or data holder object, then other elements like `DKQ` or `Q4` are implemented as `IElementHelper` and `Element.Behavior` does define which `IElementHelper` should be used,..

**Comment by thaletob** [comment]
Okay. Thank you! After testing the code and debugging it yesterday I can understand the structure of your code now. :)

**Pull request merged**
