### PR TITLE
Cleanup Matrix class

### LINKED ISSUE #72: Project cleanup: the Matrix class
As mentioned in https://github.com/BriefFiniteElementNet/BriefFiniteElement.Net/issues/36#issuecomment-673732028, here are some issues I see regarding the `Matrix` class:

1. There are approximately 70-80 public methods in the `Matrix` class and 30-40 of them are never used anywhere in the whole solution. That's about 50%. Since BFE.NET is not a linear algebra package (meaning the `Matrix` class is rather an internal implementation detail), all of this code should be removed (so it doesn't have to be maintained and tested).

2. Implementing the `IEnumerable<double>` interface doesn't make too much sense. It's only used in `DkqHelper` (line 309) for LINQ, but `[matrix].Max(i=>Math.Abs(i))` could easily be written as `[matrix].CoreArray.Max(i=>Math.Abs(i))`.

3. There are a few methods dealing with matrix inversion (`Determinant`, `Inverse`, `Inverse2`, `Solve`). This could all be handled with LU factorization. Why are there two `Invert` methods? Missing documentation!

4. Code duplication:
* line 457: `Matrix Multiply(Matrix m1, Matrix m2)` vs `void Multiply(Matrix m1, Matrix m2, Matrix result)`
* line 1596: `Matrix operator +(Matrix mat1, Matrix mat2)` vs `void Plus(Matrix mat1, Matrix mat2, Matrix result)`

5. Avoid memory allocations or at least provide an alternative. For example line 977, `Matrix ExtractRow(int i)` should have a twin `void ExtractRow(int i, Matrix target)`. Using a `double` array would be even better, why is it a `Matrix`? Missing documentation!

6. Line 612: `public static double[] Multiply(Matrix m, double[] vec)`. Why is this a static method and not a class method?

7. There's a mysterious `#region nonzero Pattern` region at the end of the file. It is used in `SparseMatrixMultiplyValidation`, but why is it part of the `Matrix` class?

8. Line 684: `Dictionary<int, int> dists = new Dictionary<int, int>()`? Not used anywhere!

Many of the points above could be labeled _messy code_ and are not related to the matrix/linear algebra subject (which I chose for obvious reasons). I haven't looked at any other classes, but the problem I see is that a user or potential contributor cannot _guess_ the intent of the code, so it will be hard to clean it up (for any other person than you @epsi1on ).

Regarding the `Matrix` class: I'd suggest to replace it with the `DenseMatrix` class of CSparse. Missing functionality could be added using extension methods or by moving the code to CSparse. I'm also thinking about adding some dense factorizations to CSparse, which would address point 3 from above list.

### PR DESCRIPTION
**Pull request by wo80**
This closes #72 .

The Matrix class now derives from CSparse.Double.DenseMatrix. The class wasn't removed completely due to the use of operator overloads, which aren't implemented in CSparse. If those were replaced by method calls, the class could be removed. Most static and member methods are converted to extensions methods.

I didn't touch the actual matrix pooling, but the (empty) finalizer and the matrix instance counter were removed.

Please review carefully.

### CODE REVIEW

**Comment by epsi1on** [comment]
Tomorrow I'll do the test and merge this PR.
I've got full Jetbrains free license for opensource contributors do you need one?
If yes, could you please send me an email ? my email address available in my github profile.
Thanks

**Comment by wo80** [comment]
Take your time with testing and make sure that all element types are working.

I don't need a Jetbrains license right now, but I might come back to your offer, thanks! Which products are included?

**Comment by epsi1on** [comment]
> Which products are included?
Not sure but I think it is a full license which includes all products, or at least JetBrain Ultimate!

**Comment by epsi1on** [comment]
Seems working good. 
You did already mentioned to use nuget for ArrayPool instead of built-in array pool. BFE is compatible with NET4 But [System.Buffers](https://www.nuget.org/packages/System.Buffers/4.5.1) needs at least .NET 4.5 so i need to remove compatibility with NET4 and minimum version would be 4.5. What you do think? having support for NET4 is not critical, but i think better to keep compatibility with older dotnets.

**Comment by wo80** [comment]
> Seems working good.

👍 

> You did already mentioned to use nuget for ArrayPool instead of built-in array pool. BFE is compatible with NET4 But [System.Buffers](https://www.nuget.org/packages/System.Buffers/4.5.1) needs at least .NET 4.5 so i need to remove compatibility with NET4 and minimum version would be 4.5. What you do think? having support for NET4 is not critical, but i think better to keep compatibility with older dotnets.

Let discuss this in a separate issue.

**Review by epsi1on — APPROVED** [review]

**Pull request merged**
