### PR TITLE
Update on ConvertBendingStressToCauchyTensor

### PR DESCRIPTION
**Pull request by rubsy92**

### CODE REVIEW

**Comment by epsi1on** [comment]
in this code

if (lambda > 0)
                {
                    //top -> add bending stress
                    buf += gst.BendingTensor.ConvertBendingStressToCauchyTensor(z);
                    buf += gst.BendingTensor.ConvertBendingStressToCauchyTensor(thickness, lambda);
                }
                else
                {
                    //bottom -> subtract bending stress
                    buf -= gst.BendingTensor.ConvertBendingStressToCauchyTensor(z);
                    buf -= gst.BendingTensor.ConvertBendingStressToCauchyTensor(thickness, lambda);
                }

if lambda is negative, then result is wrong, because negativeness of lambda is taken into account in `ConvertBendingStressToCauchyTensor` but you are considering it again...

**Comment by epsi1on** [comment]
Hello,
I am not sure if am right on above comment.
Also please note the `FlatShellStressTensor` is going to be deprecated...

**Comment by epsi1on** [comment]
Dear, I did minor changes, can you please do a review?
thanks

**Comment by rubsy92** [comment]
Hi, I'm sorry for the delay - I've been on holidays. 

Concerning the code: I think that your change on the ConvertBendingStressToCauchyTensor method is not correct... My validation example (hinged plate loaded in bending) yields 0 stress... When I keep the original code I get correct results. I made a new pull request which modifies the code back. The pull request also adds code for the GetLocalInternalStressAt for the q4 elements, as well as a method which allows for Sectionpoints (top/bottom/envelope).

**Pull request merged**
